# Generated by Django 4.0.2 on 2022-02-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(allow_unicode=True, unique=True),
        ),
    ]
